# Generated by Django 3.0.8 on 2020-09-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200903_1838'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Teklif', 'verbose_name_plural': 'Teklifler'},
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Teklif Tarihi'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BEKLEMEDE'), (2, 'İPTAL'), (3, 'SATILDI'), (4, 'KAYIP')], default=1, verbose_name='Durum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Rapor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Machine', verbose_name='Tezgah'),
        ),
    ]
