# Generated by Django 3.0.8 on 2020-09-03 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0002_auto_20200903_1838'),
        ('offer', '0002_auto_20200903_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine', verbose_name='Tezgah'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Personel'),
        ),
    ]
