# Generated by Django 3.0.8 on 2020-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20200903_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='note',
            field=models.TextField(blank=True, verbose_name='Teklif Notu'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Teklif Tarihi'),
        ),
    ]
