# Generated by Django 3.0.8 on 2020-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_auto_20200903_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BEKLEMEDE'), (2, 'İPTAL'), (3, 'SATILDI'), (4, 'KAYIP')], default=1, verbose_name='Durum'),
        ),
    ]
