# Generated by Django 3.0.8 on 2020-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20200904_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_number',
            field=models.CharField(default='sad', max_length=100, unique=True, verbose_name='Teklif Kodu'),
            preserve_default=False,
        ),
    ]
