# Generated by Django 3.0.8 on 2020-09-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Tezgah', 'verbose_name_plural': 'Tezgahlar'},
        ),
    ]
