# Generated by Django 3.0.8 on 2020-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200903_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_company',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A Markası'), (2, 'B Markası')], default=1, verbose_name='Tezgah Markası'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CNC Talaşlı İmalat Teknolojileri'), (2, 'Saç İşleme Makinaları')], default=1, verbose_name='Tezgah Tipi'),
            preserve_default=False,
        ),
    ]
