# Generated by Django 3.0.8 on 2020-09-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20200904_1229'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='customer',
        ),
        migrations.AddField(
            model_name='interviews',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offer.Offer', verbose_name='Teklif'),
            preserve_default=False,
        ),
    ]
