# Generated by Django 3.0.8 on 2020-09-03 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200902_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_contact_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 3, 17, 3, 0, 788132, tzinfo=utc), verbose_name='İlk İlişki Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_mail1',
            field=models.CharField(default='sadsa', max_length=100, verbose_name='1.İlgili Kişi E-Posta Adresi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_mail2',
            field=models.CharField(blank=True, default='sdas', max_length=100, verbose_name='2.İlgili Kişi E-Posta Adresi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_name1',
            field=models.CharField(default='sdas', max_length=100, verbose_name='1.İlgili Kişi Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_name2',
            field=models.CharField(blank=True, max_length=100, verbose_name='2.İlgili Kişi Adı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_phone1',
            field=models.CharField(max_length=11, verbose_name='1.İlgili Kişi Cep Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_phone2',
            field=models.CharField(blank=True, max_length=11, verbose_name='2.İlgili Kişi Cep Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_title1',
            field=models.CharField(max_length=100, verbose_name='1.İlgili Ünvanı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='related_person_title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='2.İlgili Ünvanı'),
        ),
    ]
